### ISSUE TITLE
Live Demo Website (jsfiddle)

### ISSUE THREAD

**Issue by zuphilip** [zotero/publications#43]
It would be nice to have a live demo website maybe on [jsfiddle](https://jsfiddle.net/). This would help to get some visual impression and allow a user to play around immediately with the html, css, javascript. I guess it is just about copying some of the things here around, but I don't see currently how to do that exactly...

**Comment by tnajdek** [comment]
Good idea, here's a quick one: https://jsfiddle.net/tnajdek/5pnbo74t/

(also added it to the README file)

**Comment by zuphilip** [comment]
Thank you very much! The example is very much appreciated!
