### ISSUE TITLE
Replace data-urls with file-saver to fix export links not working in Firefox >= 57

### ISSUE THREAD

**Issue by tnajdek** [zotero/publications#52]
Loading data-urls to the top browser window [is no longer supported](https://bugzilla.mozilla.org/show_bug.cgi?id=1331351) as of Firefox 57.

A better solution is to use [file-saver](https://www.npmjs.com/package/file-saver) that will trigger "save file" dialog correctly in various browsers.

**Comment by dstillman** [comment]
Is this still an issue?

**Comment by tnajdek** [comment]
yes, I believe so. I'll look into this asap.

**Comment by tnajdek** [comment]
Tested with FF 57.0b14 (64-bit), doesn't seem to be happening.
