### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by rufuspollock** [zotero/publications#71]
Hi all, big fan of Zotero for many years so first a big 👍 and thanks 🙏

I'm looking for some library for presenting Zotero libraries on the web and came across this. Last commit was a couple of years ago so was wondering if still active and, if not, what else you recommended  (e.g. is this the replacement https://github.com/zotero/web-library ...?)

PS: i also came across the lower level node library https://github.com/zotero/zotero-api-node which also seems a bit inactive - i'd also like a node library as was thinking of building a JAMStack style site for this.

**Comment by tnajdek** [comment]
This project is not developed anymore though it is maintained (and still in use). You won't be able to display entire library on your page using this library (without modifying it), it only works for "My Publications".

Web Library is actively developed and we're considering making a [version that can be embedded](https://forums.zotero.org/discussion/82607/embedding-the-zotero-web-library#latest). 

For lower-level library, there is also [zotero-api-client](https://github.com/tnajdek/zotero-api-client) - which is what Web Library is using under the hood. It is actively developed and works in both Node and browser environment.
